### PR TITLE
`Pi` and `e` to `Float32` and `Float16`

### LINKED ISSUE #551: Can't compare `Float32` with `pi` on Metal
```julia
julia> map(y -> y < pi, Metal.zeros(1))
ERROR: InvalidIRError: compiling MethodInstance for (::Metal.var"#broadcast_linear#204")(::MtlDeviceVector{Bool, 1}, ::Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{…}, Tuple{…}, var"#1#2", Tuple{…}}) resulted in invalid LLVM IR
Reason: unsupported call to an unknown function (call to julia.new_gc_frame)
Stacktrace:
 [1] setprecision
   @ ./mpfr.jl:1099
 [2] _irrational_to_float
   @ ./irrationals.jl:82
 [3] Type
   @ ./mathconstants.jl:30
 [4] <
   @ ./irrationals.jl:110
 [5] #1
   @ ./REPL[15]:1
 [6] _broadcast_getindex_evalf
   @ ./broadcast.jl:678
 [7] _broadcast_getindex
   @ ./broadcast.jl:651
 [8] getindex
   @ ./broadcast.jl:610
 [9] broadcast_linear
   @ ~/.julia/packages/Metal/N2ABH/src/broadcast.jl:89
Reason: unsupported call to an unknown function (call to julia.get_gc_frame_slot)
Stacktrace:
 [1] setprecision
   @ ./mpfr.jl:1099
 [2] _irrational_to_float
   @ ./irrationals.jl:82
 [3] Type
   @ ./mathconstants.jl:30
 [4] <
   @ ./irrationals.jl:110
 [5] #1
   @ ./REPL[15]:1
 [6] _broadcast_getindex_evalf
   @ ./broadcast.jl:678
 [7] _broadcast_getindex
   @ ./broadcast.jl:651
 [8] getindex
   @ ./broadcast.jl:610
 [9] broadcast_linear
   @ ~/.julia/packages/Metal/N2ABH/src/broadcast.jl:89
[...]
```
Further down, I get some `Reason: unsupported use of double value`.

```julia
julia> Metal.versioninfo()
macOS 15.1.1, Darwin 24.3.0

Toolchain:
- Julia: 1.11.3
- LLVM: 16.0.6

Julia packages: 
- Metal.jl: 1.5.1
- GPUArrays: 11.2.2
- GPUCompiler: 1.1.1
- KernelAbstractions: 0.9.33
- ObjectiveC: 3.4.0
- LLVM: 9.2.0
- LLVMDowngrader_jll: 0.6.0+0

1 device:
- Apple M2 Pro (72.219 MiB allocated)
```

### PR DESCRIPTION
**Pull request by christiangnrd**
Bypasses the conversion to `BigFloat` when converting `pi` and `e` to `Float32` and `Float16` on gpu. Values are taken from the constants in Tables 6.5 and 6.6 of the Metal shading language [specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf).

Close #551

### CODE REVIEW

**Comment by christiangnrd** [comment]
The Metal constants seem to have the same values as `RoundNearest`. Should I instead implement the `RoundUp`/`RoundDown` behaviour that the cpu comparison uses (irrationals.jl in julia base), or should I leave it as the constants like the default Metal behaviour?

```
julia> Float32(π, RoundUp)
3.1415927f0

julia> Float32(π, RoundDown)
3.1415925f0

julia> Float16(π, RoundDown)
Float16(3.14)

julia> Float16(π, RoundUp)
Float16(3.143)

julia> Float16(π, RoundNearest)
Float16(3.14)

julia> Float32(π, RoundNearest)
3.1415927f0
```

**Comment by christiangnrd** [comment]
Latest push makes the Metal behaviour the same as cpu behaviour at least for comparisons.

File: src/device/intrinsics/math.jl [hunk 1]
```diff
@@ -8,6 +8,19 @@ using Base.Math: throw_complex_domainerror
...
+@device_override Core.Float32(::typeof(π), ::RoundingMode{:Down}) = reinterpret(Float32, 0x40490fda) # 3.1415925f0 prevfloat(reinterpret(UInt32,Float32(reinterpret(Float64,0x400921FB60000000))))
+@device_override Core.Float16(::typeof(π), ::RoundingMode{:Up}) = reinterpret(Float16, 0x4249)       # Float16(3.143)
+@device_override Core.Float16(::typeof(π), ::RoundingMode) = reinterpret(Float16, 0x4248)            # Float16(3.14)
+
+# ℯ
+@device_override Core.Float32(::typeof(ℯ), ::RoundingMode{:Up}) = reinterpret(Float32, 0x402df855)   # 2.718282f0 nextfloat(reinterpret(UInt32,Float32(reinterpret(Float64,0x4005BF0A80000000))))
+@device_override Core.Float32(::typeof(ℯ), ::RoundingMode) = reinterpret(Float32, 0x402df854)        # 2.7182817f0 reinterpret(UInt32,Float32(reinterpret(Float64,0x4005BF0A80000000)))
+@device_override Core.Float16(::typeof(ℯ), ::RoundingMode) = reinterpret(Float16, 0x4170)            # Float16(2.719)
+@device_override Core.Float16(::typeof(ℯ), ::RoundingMode{:Down}) = reinterpret(Float16, 0x416f)     # Float16(2.717)
```
Comment (maleadt) [inline src/device/intrinsics/math.jl:22]: Is it possible to generate those definitions with some metaprogramming, computing the constants on the fly, instead of hard-coding them?

Comment (maleadt) [reply src/device/intrinsics/math.jl]: > @device_override $T(::typeof($irr), ::typeof($r)) = @_const_convert($irr, $T, $r)

Why the need for an extra macro? Can't you `@eval @device_override Core.Float32($(...), $(...)) = reinterpret(Float32, $(reinterpret(UInt32, Float32(...)))`, i.e., generating and embedding the bit pattern in the AST?

Comment (christiangnrd) [reply src/device/intrinsics/math.jl]: I originally misunderstood what you were asking. I just pushed a commit that should work once synchronization problems are resolved

**Comment by maleadt** [comment]
You're still hard-coding bit values, which you could evaluate at compile time.

I wanted to demonstrate that, but it looks like the conversions here just work as intended?

```julia
julia> @code_llvm Float32(ℯ)
; Function Signature: (::Type{Float32})(Base.Irrational{:ℯ})
;  @ irrationals.jl:252 within `Float32`
define float @julia_Float32_1770() #0 {
top:
  ret float 0x4005BF0A80000000
}

julia> @code_llvm Float32(pi)
; Function Signature: (::Type{Float32})(Base.Irrational{:π})
;  @ irrationals.jl:252 within `Float32`
define float @julia_Float32_1772() #0 {
top:
  ret float 0x400921FB60000000
}
```

Or, in the context of the original issue:

```julia
julia> f(y) = y < pi
f (generic function with 1 method)

julia> f(0.0)
true

julia> @code_llvm f(0.0)
; Function Signature: f(Float64)
;  @ REPL[6]:1 within `f`
define i8 @julia_f_1698(double %"y::Float64") #0 {
top:
; ┌ @ irrationals.jl:108 within `<`
; │┌ @ float.jl:619 within `<=`
    %0 = fcmp ole double %"y::Float64", 0x400921FB54442D18
    %1 = zext i1 %0 to i8
    ret i8 %1
; └└
}
```

So this shouldn't be needed. We should look into if and why these don't get constant-propagated.

**Comment by christiangnrd** [comment]
>I wanted to demonstrate that, but it looks like the conversions here just work as intended?

The actual code that's failing is the conversion from the irrational to the float with `RoundDown` or `RoundUp`. And we can see that it's also not constant-propagated on CPU in that situation:
```
julia> @code_llvm Float32(π, RoundUp)
; Function Signature: (::Type{Float32})(Base.Irrational{:π}, Base.Rounding.RoundingMode{:Up})
;  @ mathconstants.jl:29 within `Type`
define float @julia_Type_6756() #0 {
top:
;  @ mathconstants.jl:30 within `Type`
; ┌ @ irrationals.jl:82 within `_irrational_to_float`
; │┌ @ mpfr.jl:1099 within `setprecision`
    %0 = call float @"j_#setprecision#25_6761"(i64 signext 256)
    ret float %0
; └└
}
```

However I do agree that it's weird that it doesn't get const-propagated in the context of the issue.

I did finally figure out how to automate it so that it gets calculated at compile time so maybe merge and open an issue to remember to look into the constant-propagation?

**Review by maleadt — APPROVED** [review]
LGTM (to be squashed, of course).
