### PR TITLE
Fix #451 and a couple other fixes

### LINKED ISSUE #451: `unsafe_wrap(Array, ...)` of a view does not preserve offset information
he following code currently fails.
```
@testset "Issue #451" begin
        a = mtl(reshape(Float32.(1:60), 5,4,3);storage=Metal.SharedStorage)
        view_a = @view a[:,1:4,2]
        b = copy(unsafe_wrap(Array, view_a))
        c = Array(view_a)

        @test b == c
    end
```

### PR DESCRIPTION
**Pull request by christiangnrd**
Closes #451

### CODE REVIEW

File: src/array.jl [hunk 1]
```diff
@@ -556,7 +556,7 @@ Base.unsafe_convert(::Type{MTL.MTLBuffer}, A::PermutedDimsArray) =
 ## unsafe_wrap
 
 function Base.unsafe_wrap(::Type{<:Array}, arr::MtlArray{T,N}, dims=size(arr); own=false) where {T,N}
-    return unsafe_wrap(Array{T,N}, arr.data[], dims; own)
+    return unsafe_wrap(Array{T,N}, Base.unsafe_convert(MtlPtr{T}, arr), dims; own)
```
Comment (maleadt) [inline src/array.jl:559]: `pointer(...)`?

Comment (christiangnrd) [reply src/array.jl:559]: Yes.

Comment (christiangnrd) [reply src/array.jl:559]: Potential new (or maybe it's also #442) heisenbug however. The first time running the tests with that change, I got this:
```
Test Failed at /Users/christian/.julia/dev/Metal/test/mps/copy.jl:37
  Expression: dstMat == srcMat
   Evaluated: Int8[-7 -37 … -63 -108; -23 29 … 41 -111; … ; -74 -113 … -110 116; -113 55 … 88 -51] == Int8[-7 -37 … -63 -108; -23 29 … 41 -111; … ; -74 -113 … -110 116; -113 55 … 88 -51]
```
I'll comment in #442 for posterity.

**Review by tgymnich — APPROVED** [review]
