### PR TITLE
Fix loading on unsupported platforms

### LINKED ISSUE #457: [windows:] Metal does not precompile anymore when installation not functional
https://github.com/omlins/CellArrays.jl/actions/runs/11330323307/job/31507894115#step:6:433

### LINKED ISSUE #458: [MacOS:] `Metal.functional()` wrongly returns true despite no GPUs available
The following tests were executed and failed because `Metal.functional()` returned true:
https://github.com/omlins/CellArrays.jl/actions/runs/11330323307/job/31507893740#step:6:564

### PR DESCRIPTION
**Pull request by christiangnrd**
Closes #457 
Closes #458

Backport to 1.4?

### CODE REVIEW

**Comment by christiangnrd** [comment]
@omlins This makes Metal precompile for me. Can you let me know it it fixes #457 for you?

File: src/initialization.jl [hunk 1]
```diff
@@ -1,5 +1,16 @@
...
+# Starts at `nothing`. Only false when it's determined
+const _functional = Ref{Union{Nothing,Bool}}(false)
+
+function functional()
+    if isnothing(_functional[])
+        dev = device()
+
+        _functional[] =
+            supports_family(dev, MTL.MTLGPUFamilyApple7) &&
+            supports_family(dev, MTL.MTLGPUFamilyMetal3)
```
Comment (maleadt) [inline src/initialization.jl:10]: On second thought, and sorry for flip-flopping on this, we currently warn but allow working with these devices, so we probably shouldn't fail this test: https://github.com/JuliaGPU/Metal.jl/blob/ddca5c4f08f24187885556fc498856c6791bceda/src/state.jl#L18-L27

Instead, I guess the only thing we need to do here is to check if `length(devices()) > 0`?

**Comment by omlins** [comment]
> @omlins This makes Metal precompile on Windows for me. Can you let me know it it fixes #457 for you?

All the following runs should pass when the two issues #457 and #458 are resolved (currently running):
https://github.com/omlins/CellArrays.jl/actions/runs/11330323307

File: src/initialization.jl (hunk 1 above)
Comment (christiangnrd) [reply src/initialization.jl:10]: That wouldn't fix #458 though as it would still return true because the runners have graphics devices but they don't support Metal 3. I currently see this as a bug fix as I think a function called `functional` implies that the GPU works. 

If you still think it's too breaking, we should add a new convenience function that returns true only when a device is fully supported my Metal.jl as I think that's what most users are looking for; especially for CI purposes.

**Comment by christiangnrd** [comment]
@omlins You can go ahead and try out this branch. Once you confirm that it works, I'll merge this and backport to 1.4

**Comment by omlins** [comment]
> @omlins You can go ahead and try out this branch. Once you confirm that it works, I'll merge this and backport to 1.4

I'm sorry, I just realized that you would need me to test it on windows. :) Unfortunately, I don't have a windows machine. Given that it works for you, I assume you can be confident enough to release it. Then, I can confirm you that it works in the CI before you do the backport.

**Comment by christiangnrd** [comment]
@omlins You can test directly on the `release-1.4` branch if you prefer.

**Comment by omlins** [comment]
https://github.com/omlins/CellArrays.jl/actions/runs/11380953251/job/31661322271?pr=42

**Comment by omlins** [comment]
@christiangnrd : the CI has now passed as you have probably seen. So I can also confirm from my side that the fix worked.
(the CI with Julia 1.9 still fails, because Metal v1.2 is used:
https://github.com/omlins/CellArrays.jl/actions/runs/11380953251/job/32236749235?pr=42#step:6:53 . But this is not a problem)
